### ISSUE TITLE
Problem in installing catalyticFoam in Ubuntu

### ISSUE THREAD

**Issue by alnajihu** [multiscale-catalysis-polimi/catalyticFoam#1]
Dear Mauro Bracconi,

I have an issue with installing catalyticFoam in my Ubuntu 20.04.2.0 LTS virtual machine. I followed the instructions provided in the README file, but I always get this error when running "./Allwmake"

![image](https://user-images.githubusercontent.com/64618493/123117158-306c3b80-d44a-11eb-8083-cd6005c0d928.png)

I have already installed OpenFoam8 correctly in my device, and it works well. I also installed the Compulsory libraries by the following commands:
```
sudo apt install librapidxml-dev -y
sudo apt-get install libboost-all-dev
sudo apt install libeigen3-dev
```
I also adjusted the path for the above libraries in the mybashrc file to the following:
```
export EIGEN_LIBRARY_PATH=/usr/include/eigen3
export BOOST_LIBRARY_PATH=/usr/include/boost
export RAPIDXML_LIBRARY_PATH=/usr/include/rapidxml
```
Could you please lead me to where the error might be. I suspect that I have to install OpenSMOKE++ first, but it says in the description that it is installed automatically, so I am not sure where the error might be.

Thank you for your time
Regards

**Comment by mbracconi** [comment]
The attached output is expect and does not lead to any problem in the compilation. These are warning that does not prevent the compilation. At the end of the procedure, despite such outputs, you should be able to find the solver compiled in your $FOAM_USER_APPBIN. 

In case you are not able to compile the framework, the problem lies somewhere else and we need additional information to understand what is going on.

**Comment by alnajihu** [comment]
> The attached output is expect and does not lead to any problem in the compilation. These are warning that does not prevent the compilation. At the end of the procedure, despite such outputs, you should be able to find the solver compiled in your $FOAM_USER_APPBIN.
> 
> In case you are not able to compile the framework, the problem lies somewhere else and we need additional information to understand what is going on.

Thank you for your quick response, I run the examples provided using the command `catalyticPimpleFOAM`, and they run smoothly without any problem.

Best regards
