### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ErenC1** [multiscale-catalysis-polimi/catalyticFoam#3]
Hello!

I want to use catalyticFoam, but I couldn't compile it...

I tried it with both OF8 and OF7, lib paths are assigned and I changed the line in the mybashrc accordingly to the OF version, but I got the error in each time. Complete log can be found in the attachment. I don't know what is wrong.

Steps I followed:
Git clone catalyticFoam
source OF8 or OF7
set the paths of the libs in mybashrc
set OF version in mybashrc
./Allwmake (which includes source mybashrc, so I haven't sourced mybashrc before Allwmake)

Thank you in advance,
Eren.

g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -OFVERSION=70 	-w 	-std=c++11 	-Iode 	-Ipolicies 	-DOPENSMOKE_USE_ISAT=1 	-I../libraries/odeChemistry/include 	-I../libraries/OpenSMOKEpp4catalyticFoam/include 	-I../libraries/isat 	-Iisat 	-I/usr/include/boost/include 	-I/usr/include/eigen3 	-I/usr/include/rapidxml -I/home/eren/OpenFOAM/OpenFOAM-7/src/finiteVolume/lnInclude 	-I/home/eren/OpenFOAM/OpenFOAM-7/src/fvOptions/lnInclude 	-I/home/eren/OpenFOAM/OpenFOAM-7/src/meshTools/lnInclude 	-I/home/eren/OpenFOAM/OpenFOAM-7/src/finiteVolume/cfdTools 	-I/home/eren/OpenFOAM/OpenFOAM-7/src/sampling/lnInclude -IlnInclude -I. -I/home/eren/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude -I/home/eren/OpenFOAM/OpenFOAM-7/src/OSspecific/POSIX/lnInclude   -fPIC -c catalyticPimpleFOAM.C -o Make/linux64GccDPInt32Opt/catalyticPimpleFOAM.o
cc1plus: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
/home/eren/OpenFOAM/OpenFOAM-7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/catalyticPimpleFOAM.o' failed
make: *** [Make/linux64GccDPInt32Opt/catalyticPimpleFOAM.o] Error 1
Make/options:13:12: warning: backslash-newline at end of file
 EXE_LIBS = \
             
Making dependency list for source file CHEMKIN_PreProcessor.C

[log.txt](https://github.com/multiscale-catalysis-polimi/catalyticFoam/files/8488931/log.txt)

**Comment by mbracconi** [comment]
Dear @ErenC1,

The error appears just when you compile catalyticFoam and does not occur when you compile the other executables and libraries which uses the same flags.
Did you modify the Make/options in the solver folder?
Which gcc version are you using?

**Comment by ErenC1** [comment]
Hello again @mbracconi,

gcc version I use is 7.5.0, I haven't changed anything, here is the corresponding catalyticFoam/solver/Make/options:

EXE_INC = \
	$(OFVERSION) \
	-w \
	-std=c++11 \
	-Iode \
	-Ipolicies \
	$(ISAT_SUPPORT) \
	-I../libraries/odeChemistry/include \
	-I../libraries/OpenSMOKEpp4catalyticFoam/include \
	-I../libraries/isat \
	-Iisat \
	-I$(BOOST_LIBRARY_PATH)/include \
	-I$(EIGEN_LIBRARY_PATH) \
	-I$(RAPIDXML_LIBRARY_PATH) \
	-I$(LIB_SRC)/finiteVolume/lnInclude \
	-I$(LIB_SRC)/fvOptions/lnInclude \
	-I$(LIB_SRC)/meshTools/lnInclude \
	-I$(LIB_SRC)/finiteVolume/cfdTools \
	-I$(LIB_SRC)/sampling/lnInclude

EXE_LIBS = \
        -L$(FOAM_USER_LIBBIN) \
	-L../libraries/OpenSMOKEpp4catalyticFoam/lib \
	-L../libraries/odeChemistry/lib \
	-L$(BOOST_LIBRARY_PATH)/lib \
	$(CATFOAM_LIBS) \
	-lfiniteVolume \
	-lfvOptions \
	-lmeshTools \
	-lsampling \
	-lgfortran

**Comment by mbracconi** [comment]
Hi @ErenC1,
I have doublechecked the compilation files and I am not able to reproduce the error. Have you tried to clone again the repo and reinstall from scratch?

**Comment by mbracconi** [comment]
Hi @ErenC1,
I think you have modified the `mybash` in an unproper way.
By looking at you error log, it appear that the OpenFoam version is defined as `-OFVERSION=70`. However, it is supposed to be: `-DOFVERSION=70`.
Could you please doublecheck the `mybashrc` file and that option?

**Comment by ErenC1** [comment]
Hello @mbracconi,

You were right, now I can compile it without problems in both versions. Thank you for taking your time to helping me.
You'll get few citations from me in next years! 

Best regards,
Eren.
