### ISSUE TITLE
Kinetic preprocessor - mistake in units in SurfaceSummary.out?

### ISSUE THREAD

**Issue by torstein-F** [multiscale-catalysis-polimi/catalyticFoam#4]
Dear developers, 

In the file SurfaceSummary.out generated by the kinetic proprocessor, it says in the heading of the chemical reaction section:
" Units: [kmol, m3, s] and [cal/mol]"

However, in Section 5.5 of the Surface Chemkin manual, it says that the units of the pre-exponential factor, A, are cm, sec, K, mole. 
It makes me worried when I see statements about the units that are different from what I expected. It would therefore be very helpful if you could check what the correct units should be. 

Thanks for your help.

**Comment by mbracconi** [comment]
The kinetic preprocessor requires to receive as input what is specified in the CHEMKIN manual. 
The values reported in the SurfaceSummary.out correspond to the value of the reaction rates that are used in the catalyticFoam code which are in kmol, m2, s
