### ISSUE TITLE
Problems encountered by compilation

### ISSUE THREAD

**Issue by WangYijun2022** [multiscale-catalysis-polimi/catalyticFoam#6]
![屏幕截图 2024-03-18 210539](https://github.com/multiscale-catalysis-polimi/catalyticFoam/assets/116536437/340a8bde-05c2-4652-89c8-055c37271de5)
There are some problems I met, I don't see the /opt/openfoam9/src/fvOptions in openfoam-9. Is it because of this that many files cannot be found later? I don't think my Compulsory path is wrong. By the way, my fatal error is that its out of memory. If I have enough memory, if it will compilate successfully? Or keep repeating the "Can't find file"error until a fatal error occurs where an important file cannot be found, causing it to stop?
How can I solve it?

**Comment by S-Explorer** [comment]
hey Yijun : 

I think this error is just the result of an `OpenFOAM` file structure change, you can add the header file directory you want to import in `Make/Options`, note that it is `lnInclude`(those header not real header, just soft link)

find you need, and append :
```
EXE_INC = \
    -I./fluid \
    ...
    -I$(LIB_SRC)/you_find_path/lnInclude \
    ...
``` 

do not forget append `EXE_LIBS`,

good luck @WangYijun2022

**Comment by mbracconi** [comment]
Dear @WangYijun2022,

Thank you for pointing out that warning. We have solved the problem.
Moreover, the "Could not open ..." are warnings and you do not have to care about them.
By having enough memory, you should be able to compile. We have several users on OpenFOAM-9 and they work without problem.

Mauro
